name: Deploy Website to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'inked-website/**'
      - '.github/workflows/deploy-website.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./inked-website
        run: npm install

      - name: Build React App
        working-directory: ./inked-website
        run: npm run build
