name: Deploy Website to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'inked-website/**'
      - '.github/workflows/deploy-website.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/inked-website
            git pull origin main
            cd inked-website
            npm install
            npm run build
